### PR TITLE
Add trait StreamOperation with stop_operation, wrapper SubscriptionStream.

### PR DESCRIPTION
**Pull request by BratSinot**
Implements #18 
Based on errors https://github.com/obmarg/graphql-ws-client/pull/17

### CODE REVIEW

**Comment by obmarg** [comment]
Hey @BratSinot - this looks good at first glance.  Do you mind merging/rebasing in master please and then I'll take another look.  Thanks

**Comment by BratSinot** [comment]
> Hey @BratSinot - this looks good at first glance. Do you mind merging/rebasing in master please and then I'll take another look. Thanks

Done.

**Comment by BratSinot** [comment]
I'm not sure about returning `impl StreamOperation + Stream<Item = Operation::Response>`. I'm still learning Rust and didn't find the way to combine traits together.

**Comment by obmarg** [comment]
> I'm not sure about returning `impl StreamOperation + Stream<Item = Operation::Response>`. I'm still learning Rust and didn't find the way to combine traits together.
> And returning struct will be pain because of `receiver.map(move |response| op.decode(response).unwrap())`. For same reason I return `trait StreamOperation + Stream`.

Yeah, this is a good point.  I may take a closer look at this before I merge.  

Sorry it's taking me so long to get back to you on all these reviews - been a busy week at work and haven't had much time for side projects.  Thanks for your patience (and of course the contributions) 🙏

**Comment by obmarg** [comment]
I've taken your code and tried to simplify it a bit @BratSinot - it now just returns a concrete type rather than an `impl StreamOperation + Stream`.   Thought it was simpler that way.

Closing this in favour of #23 (which is based off this branch, just couldn't figure out how to push to this PR easily).

I still want to do a bit of work to get an `impl Drop` on the `SubscriptionStream`, but it'll need more work than I have the time for just now.

**Pull request closed without merging**
